CREATE SCHEMA IF NOT EXISTS identity;
CREATE SCHEMA IF NOT EXISTS tenant;
CREATE SCHEMA IF NOT EXISTS party;
CREATE SCHEMA IF NOT EXISTS product;
CREATE SCHEMA IF NOT EXISTS quote;
CREATE SCHEMA IF NOT EXISTS policy;
CREATE SCHEMA IF NOT EXISTS claims;
CREATE SCHEMA IF NOT EXISTS ledger;
CREATE SCHEMA IF NOT EXISTS settlement;
CREATE SCHEMA IF NOT EXISTS integrations;
CREATE SCHEMA IF NOT EXISTS compliance;
CREATE SCHEMA IF NOT EXISTS platform;
CREATE TABLE tenant.organizations(id uuid PRIMARY KEY,name text NOT NULL,kind text NOT NULL);
CREATE TABLE party.parties(id uuid PRIMARY KEY,kind text NOT NULL CHECK(kind IN('PERSON','ORGANIZATION')),name text NOT NULL);
CREATE TABLE identity.users(id uuid PRIMARY KEY,tenant_id uuid NOT NULL REFERENCES tenant.organizations,party_id uuid NOT NULL REFERENCES party.parties,email text NOT NULL UNIQUE,name text NOT NULL,role text NOT NULL CHECK(role IN('CUSTOMER','UNDERWRITER','ADJUSTER','FINANCE','FINANCE_APPROVER','ADMIN','DEVELOPER')),password_hash text NOT NULL,totp_secret text,disabled boolean NOT NULL DEFAULT false);
CREATE TABLE identity.sessions(token_hash text PRIMARY KEY,user_id uuid NOT NULL REFERENCES identity.users,expires_at timestamptz NOT NULL);
CREATE TABLE identity.rate_limits(key text PRIMARY KEY,attempts int NOT NULL,expires_at timestamptz NOT NULL);
CREATE TABLE product.products(id uuid PRIMARY KEY,tenant_id uuid NOT NULL REFERENCES tenant.organizations,name text NOT NULL,category text NOT NULL,description text NOT NULL);
CREATE TABLE product.versions(id uuid PRIMARY KEY,product_id uuid NOT NULL REFERENCES product.products,tenant_id uuid NOT NULL REFERENCES tenant.organizations,revision int NOT NULL,currency text NOT NULL CHECK(currency ~ '^[A-Z]{3}$'),base_premium_minor bigint NOT NULL CHECK(base_premium_minor>0),coverages jsonb NOT NULL,rating_version text NOT NULL DEFAULT 'sandbox-rating-v1',terms text NOT NULL,jurisdiction text NOT NULL DEFAULT 'SANDBOX',status text NOT NULL CHECK(status IN('DRAFT','PUBLISHED')),created_by uuid,approved_by uuid,CHECK(status!='PUBLISHED' OR created_by IS DISTINCT FROM approved_by),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(product_id,revision));
CREATE TABLE quote.quotes(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,party_id uuid NOT NULL,product_id uuid NOT NULL REFERENCES product.products,product_version_id uuid NOT NULL REFERENCES product.versions,status text NOT NULL,version int NOT NULL DEFAULT 1,snapshot jsonb NOT NULL,total_minor bigint NOT NULL CHECK(total_minor>0),currency text NOT NULL,expires_at timestamptz NOT NULL,underwriter_id uuid,underwriting_reason text,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,id));
CREATE TABLE policy.policies(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,party_id uuid NOT NULL,quote_id uuid NOT NULL UNIQUE,number text NOT NULL UNIQUE,status text NOT NULL,version int NOT NULL DEFAULT 1,snapshot jsonb NOT NULL,premium_minor bigint NOT NULL,currency text NOT NULL,effective_at timestamptz NOT NULL,expires_at timestamptz NOT NULL,carrier_reference text NOT NULL,renewed_from uuid,created_at timestamptz NOT NULL DEFAULT now(),CHECK(effective_at<expires_at),UNIQUE(tenant_id,id));
CREATE TABLE policy.revisions(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,party_id uuid NOT NULL,policy_id uuid NOT NULL,revision int NOT NULL,snapshot jsonb NOT NULL,reason text NOT NULL,effective_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,policy_id,revision),FOREIGN KEY(tenant_id,policy_id) REFERENCES policy.policies(tenant_id,id));
CREATE TABLE claims.claims(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,party_id uuid NOT NULL,policy_id uuid NOT NULL,status text NOT NULL,version int NOT NULL DEFAULT 1,incident_at timestamptz NOT NULL,description text NOT NULL,requested_minor bigint NOT NULL CHECK(requested_minor>0),approved_minor bigint NOT NULL DEFAULT 0,paid_minor bigint NOT NULL DEFAULT 0,currency text NOT NULL,proposed_by uuid,approved_by uuid,reason text,coverage_snapshot jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),CHECK(paid_minor>=0 AND paid_minor<=approved_minor),FOREIGN KEY(tenant_id,policy_id) REFERENCES policy.policies(tenant_id,id),UNIQUE(tenant_id,id));
CREATE TABLE claims.allocations(tenant_id uuid NOT NULL,policy_id uuid NOT NULL,committed_minor bigint NOT NULL DEFAULT 0 CHECK(committed_minor>=0),PRIMARY KEY(tenant_id,policy_id),FOREIGN KEY(tenant_id,policy_id) REFERENCES policy.policies(tenant_id,id));
CREATE TABLE claims.documents(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,party_id uuid NOT NULL,claim_id uuid NOT NULL,object_key text NOT NULL,filename text NOT NULL,mime text NOT NULL,sha256 text NOT NULL,status text NOT NULL CHECK(status IN('QUARANTINED','CLEAN','REJECTED')),created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(tenant_id,claim_id) REFERENCES claims.claims(tenant_id,id));
CREATE TABLE ledger.journals(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,reference text NOT NULL,currency text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),creation_tx xid8 NOT NULL DEFAULT pg_current_xact_id(),UNIQUE(tenant_id,reference),UNIQUE(tenant_id,id));
CREATE TABLE ledger.postings(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,journal_id uuid NOT NULL,account text NOT NULL,side text NOT NULL CHECK(side IN('DEBIT','CREDIT')),amount_minor bigint NOT NULL CHECK(amount_minor>0),FOREIGN KEY(tenant_id,journal_id) REFERENCES ledger.journals(tenant_id,id));
CREATE TABLE settlement.batches(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,status text NOT NULL,amount_minor bigint NOT NULL CHECK(amount_minor>0),currency text NOT NULL,proposed_by uuid NOT NULL,approved_by uuid,reason text NOT NULL,version int NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE integrations.api_keys(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,owner_id uuid NOT NULL,name text NOT NULL,prefix text NOT NULL,secret_hash text NOT NULL UNIQUE,created_at timestamptz NOT NULL DEFAULT now(),revoked_at timestamptz);
CREATE TABLE integrations.webhooks(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,owner_id uuid NOT NULL,url text NOT NULL,signing_secret text NOT NULL,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE integrations.deliveries(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,subscription_id uuid NOT NULL,event_id uuid NOT NULL,payload jsonb NOT NULL,status text NOT NULL DEFAULT 'PENDING',attempts int NOT NULL DEFAULT 0,next_attempt_at timestamptz NOT NULL DEFAULT now(),last_http_status int,UNIQUE(subscription_id,event_id));
CREATE TABLE compliance.audit(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,actor_id uuid NOT NULL,action text NOT NULL,resource_id uuid,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE platform.idempotency(tenant_id uuid NOT NULL,actor_id uuid NOT NULL,route text NOT NULL,key text NOT NULL,payload_hash text NOT NULL,response jsonb,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(tenant_id,actor_id,route,key));
CREATE TABLE platform.operations(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,party_id uuid NOT NULL,actor_id uuid NOT NULL,kind text NOT NULL,resource_id uuid NOT NULL,status text NOT NULL DEFAULT 'PENDING',stage text NOT NULL DEFAULT 'CREATED',payload jsonb NOT NULL DEFAULT '{}',provider_reference text,policy_id uuid,error_code text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(kind,resource_id));
CREATE TABLE platform.outbox(id uuid PRIMARY KEY,tenant_id uuid NOT NULL,type text NOT NULL,resource_id uuid NOT NULL,payload jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),published_at timestamptz);
CREATE TABLE platform.inbox(consumer text NOT NULL,event_id uuid NOT NULL,received_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(consumer,event_id));
CREATE INDEX quote_work_queue ON quote.quotes(tenant_id,status,created_at);
CREATE INDEX policy_portfolio ON policy.policies(party_id,created_at);
CREATE INDEX claims_work_queue ON claims.claims(tenant_id,status,created_at);
CREATE INDEX outbox_pending ON platform.outbox(created_at) WHERE published_at IS NULL;
CREATE INDEX operations_pending ON platform.operations(status,updated_at);
CREATE FUNCTION platform.immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Immutable record'; END $$;
CREATE TRIGGER immutable_audit BEFORE UPDATE OR DELETE ON compliance.audit FOR EACH ROW EXECUTE FUNCTION platform.immutable();
CREATE TRIGGER immutable_revision BEFORE UPDATE OR DELETE ON policy.revisions FOR EACH ROW EXECUTE FUNCTION platform.immutable();
CREATE TRIGGER immutable_journal BEFORE UPDATE OR DELETE ON ledger.journals FOR EACH ROW EXECUTE FUNCTION platform.immutable();
CREATE TRIGGER immutable_posting BEFORE UPDATE OR DELETE ON ledger.postings FOR EACH ROW EXECUTE FUNCTION platform.immutable();
CREATE FUNCTION product.protect_published() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.status='PUBLISHED' THEN RAISE EXCEPTION 'Published product version is immutable'; END IF; RETURN NEW; END $$;
CREATE TRIGGER immutable_published BEFORE UPDATE OR DELETE ON product.versions FOR EACH ROW EXECUTE FUNCTION product.protect_published();
CREATE FUNCTION ledger.balance_check() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE jid uuid; n bigint; total numeric; BEGIN jid:=CASE WHEN TG_TABLE_NAME='journals' THEN NEW.id ELSE NEW.journal_id END; SELECT count(*),coalesce(sum(CASE WHEN side='DEBIT' THEN amount_minor::numeric ELSE -amount_minor::numeric END),0) INTO n,total FROM ledger.postings WHERE tenant_id=NEW.tenant_id AND journal_id=jid; IF n<2 OR total<>0 THEN RAISE EXCEPTION 'Unbalanced journal'; END IF; RETURN NULL; END $$;
CREATE CONSTRAINT TRIGGER journal_balanced AFTER INSERT ON ledger.journals DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION ledger.balance_check();
CREATE CONSTRAINT TRIGGER posting_balanced AFTER INSERT ON ledger.postings DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION ledger.balance_check();
CREATE FUNCTION ledger.new_journal_only() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE created xid8; BEGIN SELECT creation_tx INTO created FROM ledger.journals WHERE tenant_id=NEW.tenant_id AND id=NEW.journal_id; IF created IS DISTINCT FROM pg_current_xact_id() THEN RAISE EXCEPTION 'Journal already committed'; END IF; RETURN NEW; END $$;
CREATE TRIGGER posting_creation_only BEFORE INSERT ON ledger.postings FOR EACH ROW EXECUTE FUNCTION ledger.new_journal_only();
DO $$ DECLARE s text; t text; BEGIN
  FOR s,t IN SELECT schemaname,tablename FROM pg_tables WHERE schemaname IN('quote','policy','claims','ledger','settlement','integrations','compliance') LOOP
    EXECUTE format('ALTER TABLE %I.%I ENABLE ROW LEVEL SECURITY',s,t);
    EXECUTE format('ALTER TABLE %I.%I FORCE ROW LEVEL SECURITY',s,t);
    IF EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=s AND table_name=t AND column_name='party_id') THEN
      EXECUTE format('CREATE POLICY scoped ON %I.%I USING (tenant_id=nullif(current_setting(''app.tenant_id'',true),'''')::uuid OR (current_setting(''app.role'',true)=''CUSTOMER'' AND party_id=nullif(current_setting(''app.party_id'',true),'''')::uuid)) WITH CHECK (tenant_id=nullif(current_setting(''app.tenant_id'',true),'''')::uuid OR (current_setting(''app.role'',true)=''CUSTOMER'' AND party_id=nullif(current_setting(''app.party_id'',true),'''')::uuid))',s,t);
    ELSE
      EXECUTE format('CREATE POLICY scoped ON %I.%I USING (tenant_id=nullif(current_setting(''app.tenant_id'',true),'''')::uuid) WITH CHECK (tenant_id=nullif(current_setting(''app.tenant_id'',true),'''')::uuid)',s,t);
    END IF;
  END LOOP;
END $$;
ALTER TABLE platform.operations ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform.operations FORCE ROW LEVEL SECURITY;
CREATE POLICY operation_scope ON platform.operations USING (tenant_id=nullif(current_setting('app.tenant_id',true),'')::uuid OR (current_setting('app.role',true)='CUSTOMER' AND party_id=nullif(current_setting('app.party_id',true),'')::uuid)) WITH CHECK (tenant_id=nullif(current_setting('app.tenant_id',true),'')::uuid OR (current_setting('app.role',true)='CUSTOMER' AND party_id=nullif(current_setting('app.party_id',true),'')::uuid));
